### PR TITLE
add remove item v1

### PR DESCRIPTION
**Pull request by dominikbodzioch**
This solution is absolutely not perfect. But the more you ask me to fix, the more I will learn!
So don't hesitate to comment / review :)

Marat made some improvement in "pom". I also added some additional dependencies in my request (if merged, there will almost for sure be conflicts).

### CODE REVIEW

**Review by gercen8905 — COMMENTED** [review]
Good use of WebDriverManager. Suggest to use it in our final version. Library with logs is also nice improvement! 
My propositions:
1. Naming of test methods could be more descriptive e.g. addedItemToCartIsPresentAtCart or successfulAddingItemToCart (it will say that this scenario is positive one).
2. Not necessary to use word "Test" in the name of test method. @Test already implies.
3. Try to use @BeforeTest and @AfterTest because in every test you are using setUp and tearDown logic. Your tests will run faster if you don't quit the driver after each test.
4. About close() and quit(). If we handle one window or tab we can skip close(), this call is redundant. 
5. You have 2 tests and 6 assertions. If the first assertion will fail the test stops... I heard about good practice: one test one assertion. But Soft Assert may help if you want to leave many assertions in one test.
6. Try to extract logic of adding to cart into separate private method. DRY.
7. Recommend to use wait in line 35. When I ran the tests first time I had NSEE.
Main idea that you wrote test which work!

**Review by czajkaaga — APPROVED** [review]
It's ok. Very good job! :)

**Comment by dominikbodzioch** [comment]
Thanks @gercen8905 for valuable review!
Despite the significant changes in the structure of the code, the logic practically did not change.

**Comment by gercen8905** [comment]
Perfect!!! Maybe I was wrong in some comments, but your code looks very nice after refactoring!

**Comment by kristinapeneva** [comment]
Hello, Dominik.
I think the code is very clean and easy to understand. I really like that every step has it's own method. 
I only have a tiny feedback about "//img[@class=\\"s-image\\"]" -> line 66. Maybe you could just use single quotes ' instead of escaping double quotes with \". But it still works anyway.
Good job!

**Comment by dominikbodzioch** [comment]
> Perfect!!! Maybe I was wrong in some comments, but your code looks very nice after refactoring!

I realize that I put together something that "works" too quickly.
I can see now that I should better refactor my code before uploading it to a remote repo and making a pull request.
In real design (but here as well) it's a bit of a waste of someone else's time.
I don't think you over-criticize. What you write shows some programming experience.
Thanks!

**Comment by dominikbodzioch** [comment]
@kristinapeneva I tried to watch the single quotation marks, but before 1 am I didn't have enough concentration to catch everything :) (like you, I prefer this kind of formatting).
Thanks Kristina!

**Pull request merged**
